### ISSUE TITLE
Ownership of requests, requests3

### ISSUE THREAD

**Issue by lovelydinosaur** [python-http/discussions#5]
So, this: https://github.com/not-kennethreitz/team/issues/21

I've proposed `python-http` for `requests` - can put together something more significant as a proposal if we want to go for that.

I've also proposed that I'd like to take admin over `requests3`. (Not as a decision on "that's what I think http3 should end up as", but so that we have it as an open option.)

**Comment by sethmlarson** [comment]
Taking over requests would be something that we can do (and were essentially formed to do). It's maintenance burden is security fixes only so it's an easy candidate for long-term support under the org.

requests3 I don't really care about. There's no large user-base to look after.

Any of the other requests peripheral libraries are also things we'd be willing to take maintenance of.

**Comment by sethmlarson** [comment]
It sounds like requests will be housed under the @psf organization per the thread. Users are safe and it's out of our hands.

**Comment by njsmith** [comment]
It may work out the same, once we finish setting up python-http as an official PSF working group...

**Comment by sethmlarson** [comment]
Yeah, that's kind of what I'm expecting to happen. :)

**Comment by njsmith** [comment]
Well, maybe it's not entirely settled: https://github.com/not-kennethreitz/team/issues/21#issuecomment-512598202

I'm not going to post in that thread, but I think the PSF might be a better option in any case for right now. AFAIK the two valuable requests-related resources that Kenneth currently owns are the repo, and the `python-requests.org` domain name. The PSF has the legal apparatus set up to own a domain name; we don't. And if goes to the PSF first, then they'll probably force us to demonstrate that we're organized enough to handle it, which is honestly not a bad thing.

**Comment by lovelydinosaur** [comment]
> I think the PSF might be a better option in any case for right now.

Yes, definately happy to see the PSF step in there. Either so that they can take ownership, or so that they can be involved in vetting any handover.

**Comment by sethmlarson** [comment]
Agreed. It'll be a goal of ours to be able to handle complete transfers properly. :) @tomchristie I think KR is waiting for a reply from you in that thread?
