### ISSUE TITLE
Moving hstspreload package under the organization

### ISSUE THREAD

**Issue by sethmlarson** [python-http/discussions#7]
@kislyuk has shared the name `hstspreload` on PyPI with me and I've revamped the project to be more efficient (not loading the whole list into memory to do lookups) and to automatically deploy new versions when the Chromium HSTS Preload list is updated.

What are everyone's thoughts on moving the project under this organization?

https://github.com/sethmlarson/hstspreload
https://pypi.org/project/hstspreload

**Comment by pquentin** [comment]
I believe that this project is relevant to the organization. 👍

**Comment by sethmlarson** [comment]
I'm going to migrate the package under the organization. Thanks all! :)
